version: '3'
services:
  server:
    container_name: server-geekten_vol4_2022
    build:
      context: .
      dockerfile: ./server/Dockerfile
    env_file:
      - docker-compose.env
    ports:
      - 8000:8000
    tty: true
    volumes:
      - ./server:/go/src/github.com/Doer-org/geekten_vol4_2022
    depends_on:
      - db
    command: go run main.go

  db:
    container_name: db-geekten_vol4_2022
    build:
      context: .
      dockerfile: ./db/Dockerfile
    ports:
      - 5432:5432
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    env_file:
      - docker-compose.env
    restart: always

  proxy:
    container_name: proxy-geekten_vol4_2022
    build:
      context: .
      dockerfile: ./proxy/Dockerfile
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf # default conf
      - ./proxy/conf:/etc/nginx/conf
      - ./proxy/html:/var/www/html
    ports:
      - 80:80
    